services:
  - type: web
    name: MapEarthQ
    env: python 
    buildCommand: "./build.sh"
    startCommand: "gunicorn Project.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true