# Generated by Django 4.0.3 on 2022-04-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorldData',
            fields=[
                ('country', models.CharField(max_length=50)),
                ('Mag', models.FloatField(primary_key=True, serialize=False)),
                ('lat', models.FloatField(null=True)),
                ('lon', models.FloatField(null=True)),
                ('time', models.DateTimeField(blank=True)),
            ],
        ),
    ]
