# Generated by Django 4.0.3 on 2022-04-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapearthq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worlddata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='worlddata',
            name='Mag',
            field=models.FloatField(),
        ),
    ]
