# Generated by Django 4.0 on 2023-01-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapearthq', '0002_worlddata_id_alter_worlddata_mag'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyCsvFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='downloadable_csv')),
            ],
        ),
    ]
